"""create base tables

Revision ID: 24804d9905e1
Revises: 
Create Date: 2026-02-17 07:04:16.739657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24804d9905e1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingest_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('day_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ingest_log_symbol_day', 'ingest_log', ['symbol', 'day_utc'], unique=False)
    op.create_table('instruments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('price_scale', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('candles_1m',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('ts_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bid_o', sa.Integer(), nullable=False),
    sa.Column('bid_h', sa.Integer(), nullable=False),
    sa.Column('bid_l', sa.Integer(), nullable=False),
    sa.Column('bid_c', sa.Integer(), nullable=False),
    sa.Column('bid_v', sa.Float(), nullable=True),
    sa.Column('ask_o', sa.Integer(), nullable=True),
    sa.Column('ask_h', sa.Integer(), nullable=True),
    sa.Column('ask_l', sa.Integer(), nullable=True),
    sa.Column('ask_c', sa.Integer(), nullable=True),
    sa.Column('ask_v', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'ts_utc', name='uq_candles_1m_instrument_ts')
    )
    op.create_index('ix_candles_1m_ts_utc', 'candles_1m', ['ts_utc'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_candles_1m_ts_utc', table_name='candles_1m')
    op.drop_table('candles_1m')
    op.drop_table('instruments')
    op.drop_index('ix_ingest_log_symbol_day', table_name='ingest_log')
    op.drop_table('ingest_log')
    # ### end Alembic commands ###
